#!/bin/sh

# Integria IMS Console Installer (c) 2008-2013 Artica ST
# Linux/FreeBSD Version (generic), for SuSe, Debian/Ubuntu, RHEL/CentOS,
# Fedora and FreeBSD only
# other Linux distros could not work properly without modifications
# Please see http://www.integriaims.com
# v4.0dev
# This code is licensed under GPL 2.0 license.
# **********************************************************************

PI_VERSION=4.0dev
FORCE=0
LOG_TIMESTAMP=`date +"%Y/%m/%d %H:%M:%S"`
MODE=$1


get_distro () {

	OS_NAME=`uname -s`

	# Get Linux Distro type and version
	if [ -f "/etc/SuSE-release" ]
	then
		OS_VERSION=`cat /etc/SuSE-release | grep VERSION | cut -f 3 -d " "`
		LINUX_DISTRO=SUSE
	else
		if [ -f "/etc/lsb-release" ] && [ ! -f "/etc/redhat-release" ]
		then
			OS_VERSION=`cat /etc/lsb-release | grep DISTRIB_RELEASE | cut -f 2 -d "="`
			LINUX_DISTRO=UBUNTU
			OS_VERSION="UBUNTU $OS_VERSION"
		else
			if [ -f "/etc/debian_version" ]
			then
				OS_VERSION=`cat /etc/debian_version`
				OS_VERSION="DEBIAN $OS_VERSION"
				LINUX_DISTRO=DEBIAN
			else
				if [ -f "/etc/fedora-release" ]
				then
					OS_VERSION=`cat /etc/fedora-release | cut -f 4 -d " "`
					OS_VERSION="FEDORA $OS_VERSION"
					LINUX_DISTRO=FEDORA
				else
					if [ -f "/etc/redhat-release" ]
					then
						LINUX_DISTRO=RHEL_CENTOS
					else
						if [ "$OS_NAME" = "FreeBSD" ]
						then
							LINUX_DISTRO=FreeBSD
						else
							if [ "$OS_NAME" = "NetBSD" ]
							then
								LINUX_DISTRO=NetBSD
							else
								LINUX_DISTRO=GENERIC
							fi
						fi
						OS_VERSION=`uname -r`
					fi
				fi
			fi
		fi
	fi
	echo $LINUX_DISTRO
}

uninstall () {
	DISTRO=`get_distro`

	if [ "$DISTRO" = "UBUNTU" ]
	then
		INTEGRIA_HOME=/var/www/integria
	else
		if [ "$DISTRO" = "RHEL_CENTOS" ]
		then
			INTEGRIA_HOME=/var/www/html/integria
		else
			if [ "$DISTRO" = "FEDORA" ]
			then
				INTEGRIA_HOME=/var/www/html/integria
			else
				if [ "$DISTRO" = "FreeBSD" ]
				then
					INTEGRIA_HOME="/usr/local/www/data/integria /usr/local/www/apache22/data/integria"
				else
					if [ "$DISTRO" = "NetBSD" ]
					then
						INTEGRIA_HOME="/usr/pkg/share/httpd/htdocs/integria"
					else
						INTEGRIA_HOME=/srv/www/htdocs/integria
					fi
				fi
			fi
		fi
	fi

	echo "Removing Pandora FMS Console"
	rm -Rf $INTEGRIA_HOME
	echo "You need to drop manually pandora database from your Database server"
	echo "Done"
}

install () {

	DISTRO=`get_distro`
	OLDFILENAMETMP=`date +"%Y-%m-%d"`
	
	if [ "$DISTRO" = "UBUNTU" ]
	then
		INTEGRIA_HOME=/var/www/integria
		PANDORA_CONF=$INTEGRIA_HOME/include/config.php
	else
		if [ "$DISTRO" = "RHEL_CENTOS" ]
		then
			INTEGRIA_HOME=/var/www/html/integria
			PANDORA_CONF=$INTEGRIA_HOME/include/config.php
		else
			if [ "$DISTRO" = "FEDORA" ]
			then
				INTEGRIA_HOME=/var/www/html/integria
				PANDORA_CONF=$INTEGRIA_HOME/include/config.php
			else
				if [ "$DISTRO" = "FreeBSD" ]
				then
					if [ -d /usr/local/www/apache22 ]
					then
						INTEGRIA_HOME=/usr/local/www/apache22/data/integria
					else
						INTEGRIA_HOME=/usr/local/www/data/integria
					fi
					PANDORA_CONF=$INTEGRIA_HOME/include/config.php
				else
					if [ "$DISTRO" = "NetBSD" ]
					then
						INTEGRIA_HOME=/usr/pkg/share/httpd/htdocs/integria
						PANDORA_CONF=$INTEGRIA_HOME/include/config.php
					else
						INTEGRIA_HOME=/srv/www/htdocs/integria
						PANDORA_CONF=$INTEGRIA_HOME/include/config.php
					fi
				fi
			fi
		fi
	fi

	echo "Detecting operating system: $DISTRO"
	
	if [ -f $INTEGRIA_HOME ] && [ "$FORCE" = "0" ]
	then
		echo "Seems that default dir already exists. Please use --force to"
		echo "force installer to install on $INTEGRIA_HOME"
		exit
	else
		echo "Checking default dir $INTEGRIA_HOME..."
	fi

	# Create directories
	echo "Creating Integria IMS home directory at $INTEGRIA_HOME ..."
	mkdir -p $INTEGRIA_HOME 2> /dev/null

	# Copying Integria IMS
	echo "Copying Integria IMS to $INTEGRIA_HOME.."
	cp -R * $INTEGRIA_HOME
	chmod -R u+rwX,g+rX,g-w,o-rwx $INTEGRIA_HOME


	# Creating 'integria' user
	id integria 2> /dev/null
	if [ $? -eq 0 ]; then
		echo " "
		echo "User integria does exist, skipping this step"
	else
		echo "Creating 'integria' user"
		if [ "$DISTRO" = "FreeBSD" ]
		then
			echo "integria:41121:::::Integria IMS:/home/integria:/usr/sbin/nologin:" | adduser -f - -w no 2> /dev/null
		else
			useradd integria
			mkdir /home/pandora 2> /dev/null
			mkdir /home/pandora/.ssh 2> /dev/null
			chown -R integria /home/integria 
		fi
	fi

	if [ ! -d /var/spool/integria ]
	then
		mkdir -p /var/spool/integria
		mkdir -p /var/spool/integria/data_in
	fi

	#Ownership
	if [ "$DISTRO" = "UBUNTU" ]
	then
		chown -R www-data:root $INTEGRIA_HOME
		chown -R integria:www-data /var/spool/integria/
	else 
		if [ "$DISTRO" = "RHEL_CENTOS" ]
		then
			chown -R apache:apache $INTEGRIA_HOME
			chown -R integria:apache /var/spool/integria/	
		else 
			if [ "$DISTRO" = "FEDORA" ]
			then
				chown -R apache:apache $INTEGRIA_HOME
				chown -R integria:apache /var/spool/integria/	
			else
				if [ "$DISTRO" = "FreeBSD" -o "$DISTRO" = "NetBSD" ]
				then
					chown -R www:www $INTEGRIA_HOME
					chown -R integria:www /var/spool/integria/
				else
					# Assuming SUSE
					chown -R wwwrun:root $INTEGRIA_HOME
					chown -R integria:www /var/spool/integria/
				fi
			fi
		fi
	fi

	echo "Setting secure permissions for Intengria IMS' spool dir..."
	chmod -R u+rwX,g+rwX,o-rwx /var/spool/integria/

	echo "Done."
	echo " "
	echo "You have your Integria IMS installed on $INTEGRIA_HOME."
	echo " "
	echo "Now you can setup your Integria IMS  and install"
	echo "database using a browser and point to: "
	echo " " 
	echo "	http://ip_address_of_this_server/integria/install.php"
	echo " "
	echo " "
}

help () {
	echo "    --force-install     To force installation if already installed on this system"
	echo "    --install           To install Integria IMS on this system"
	echo " "
}

# Script banner at start
echo " "
echo "Integria IMS Installer $PI_VERSION (c) 2008-2013 ArticaST"
echo "This program is licensed under GPL2 Terms. http://integriaims.com"
echo " "

case "$MODE" in

'--force-install')
	FORCE=1
	install
	exit
	;;

'--install')
	install
	exit
	;;

'--uninstall')
	uninstall
	exit
	;;

*)
	help
esac

