<?php 

// Integria 2.0 - http://integria.sourceforge.net
// ==================================================
// Copyright (c) 2008 Artica Soluciones Tecnologicas
// Copyright (c) 2008 Esteban Sanchez, estebans@artica.es

// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; version 2
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

require_once ('include/functions_incidents.php');

$filter = array ();
$filter['string'] = (string) get_parameter ('search_string');
$filter['status'] = (int) get_parameter ('status');
$filter['priority'] = (int) get_parameter ('search_priority', -1);
$filter['id_group'] = (int) get_parameter ('search_id_group', 1);
$filter['status'] = (int) get_parameter ('search_status', 0);
$filter['id_product'] = (int) get_parameter ('search_id_product');
$filter['id_company'] = (int) get_parameter ('search_id_company');
$filter['id_inventory'] = (int) get_parameter ('search_id_inventory');
$filter['serial_number'] = (string) get_parameter ('search_serial_number');
$filter['id_building'] = (int) get_parameter ('search_id_building');
$filter['sla_fired'] = (bool) get_parameter ('search_sla_fired');
$filter['id_incident_type'] = (int) get_parameter ('search_id_incident_type');
$filter['id_user'] = (string) get_parameter ('search_id_user', '');
$filter['id_incident_type'] = (int) get_parameter ('search_id_incident_type');
$filter['id_user'] = (string) get_parameter ('search_id_user', '');
$filter['first_date'] = (string) get_parameter ('search_first_date');
$filter['last_date'] = (string) get_parameter ('search_last_date');

$statuses = get_indicent_status ();
$resolutions = get_incident_resolutions ();

echo '<div style="width: 950px;">';
echo '<h1>'.__('Incidents report').'</h1>';

$generated_str = '<div class="report_info" style="text-align: right; width: 95%;">';
$generated_str .= print_label (__('Generated by').' : ', '', '', true,
	dame_nombre_real ($config['id_user']));
$generated_str .= '<br />';
$generated_str .= print_label (__('Date').' : ', '', '', true, date ('Y-m-d H:i', time ()));
$generated_str .= '</div>';

echo $generated_str;

$output = '<div style="margin-left: 15px; text-align: left; width: 95%;">';

/* Show search criterium */
if (! empty ($filter['string'])) 
	$output .= print_label (__('Containing').': ', '', '', true,
		'"'.$filter['string'].'"').'<br />';
if (! empty ($filter['status']))
	$output .= print_label (__('Status').': ', '', '', true,
		$statuses[$filter['status']]).'<br />';
if ($filter['priority'] != -1)
	$output .= print_label (__('Priority').': ', '', '', true,
		print_priority_flag_image ($filter['priority'], true)).'<br />';
if ($filter['id_group'] != 1)
	$output .= print_label (__('Group').': ', '', '', true,
		get_db_value ('nombre', 'tgrupo', 'id_grupo', $filter['id_group'])).'<br />';
if (! empty ($filter['sla_fired']))
	$output .= print_label (__('SLA fired').': ', '', '', true, __('Yes')).'<br />';
if (! empty ($filter['id_product']))
	$output .= print_label (__('Product').': ', '', '', true, 
		get_db_value ('name', 'tkb_product', 'id', $filter['id_product'])).'<br />';
if (! empty ($filter['id_company']))
	$output .= print_label (__('Company').': ', '', '', true,
		get_db_value ('name', 'tinventory', 'id', $filter['id_company'])).'<br />';
if (! empty ($filter['id_inventory']))
	$output .= print_label (__('Inventory').': ', '', '', true,
		get_inventory_name ($filter['id_inventory'])).'<br />';
if (! empty ($filter['serial_number']))
	$output .= print_label (__('Serial number').': ', '', '', true,
		$filter['serial_number']).'<br />';
if (! empty ($filter['id_building']))
	$output .= print_label (__('Building').': ', '', '', true, 
		get_db_value ('name', 'tbuilding', 'id', $filter['id_building'])).'<br />';
if (! empty ($filter['id_user']))
	$output .= print_label (__('User').': ', '', '', true,
		$filter['id_user']).'<br />';
if (! empty ($filter['id_incident_type']))
	$output .= print_label (__('Incident type').': ', '', '', true,
		get_db_value ('name', 'tincident_type', 'id',
		$filter['id_incident_type'])).'<br />';
if (! empty ($filter['first_date']))
	$output .= print_label (__('From').': ', '', '', true,
		$filter['first_date']).'<br />';
if (! empty ($filter['last_date']))
	$output .= print_label (__('To').': ', '', '', true,
		$filter['last_date']).'<br />';

$output .= '</div>';
echo '<div class="report_info" style="text-align: left; width: 95%">';
if ($output != '') {
	echo $output;
} else {
	echo __('All incidents');
}
echo '</div>';

$table->class = 'listing';
$table->width = "95%";
$table->style = array ();
$table->style[0] = 'font-weight: bold';
$table->head = array ();
$table->head[0] = __('ID');
$table->head[1] = __('SLA');
$table->head[2] = __('Incident');
$table->head[3] = __('Group');
$table->head[4] = __('Status')."<br /><em>".__('Resolution')."</em>";
$table->head[5] = __('Priority');
$table->head[6] = __('Updated')."<br /><em>".__('Started')."</em>";
$table->head[7] = __('Work');
$table->head[8] = __('Responsible');
$table->data = array ();

$incidents = filter_incidents ($filter);

echo '<h3>'.__('Statistics').'</h3>';

print_incidents_stats ($incidents);
echo '<div style="clear: both"></div>';

if ($incidents === false) {
	$table->colspan[0][0] = 9;
	$table->data[0][0] = __('Nothing was found');
	$incidents = array ();
}

foreach ($incidents as $incident) {
	$data = array ();
	
	$data[0] = '#'.$incident['id_incidencia'];
	$data[1] = '';
	if ($incident["affected_sla_id"] != 0)
		$data[1] = '<img src="images/exclamation.png" />';
	$data[2] = '<a href="index.php?sec=incidents&sec2=operation/incidents/incident&id='.$incident['id_incidencia'].'">'.
		$incident['titulo'].'</a>';
	$data[3] = get_db_value ("nombre", "tgrupo", "id_grupo", $incident['id_grupo']);
	
	$resolution = isset ($resolutions[$incident['resolution']]) ? $resolutions[$incident['resolution']] : __('None');
	
	$data[4] = '<strong>'.$statuses[$incident['estado']].'</strong><br /><em>'.$resolution.'</em>';
	$data[5] = print_priority_flag_image ($incident['prioridad'], true);
	$data[6] = human_time_comparation ($incident["actualizacion"]);
	$data[6] .= '<br /><em>';
	$data[6] .=  human_time_comparation ($incident["inicio"]);
	$data[6] .= '</em>';
	
	$data[7] = '';
	$workunits = get_incident_count_workunits ($incident["id_incidencia"]);
	if ($workunits > 0) {
		$data[7] = '<img src="images/award_star_silver_1.png" />';
		$data[7] .= get_incident_workunit_hours ($incident["id_incidencia"]);
	}
	
	$data[8] = $incident['id_usuario'];
	
	array_push ($table->data, $data);
}

echo '<h3>'.__('Incident list').'</h3>';

print_table ($table);

/* Print a cute application logo */
echo '<div style="width: 95%; text-align: left; ">';
include ('general/footer.php');
echo '</div>';
echo "</div>";
?>
<script language="JavaScript" src="include/FusionCharts/FusionCharts.js"></script>
