<?php

// Integria IMS - http://integria.sourceforge.net
// ==================================================
// Copyright (c) 2011-2011 Artica Soluciones Tecnologicas

// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; version 2
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
global $config;
require_once ('include/functions_incidents.php');

check_login ();

$id_incident = get_parameter('id', 0);
$clean_output = get_parameter('clean_output', 0);

$statuses = get_indicent_status ();
$resolutions = get_incident_resolutions ();

echo '<div style="width: 950px;">';
echo '<h1>'.__("Incident #$id_incident report");

if ($clean_output == 0){
	// link full screen
	echo "&nbsp;&nbsp;<a title='Full screen' href='index.php?sec=incidents&sec2=operation/incidents/incident_report&id=$id_incident&clean_output=1'>";
	echo "<img src='images/html.png'>";
	echo "</a>";

	// link PDF report
	echo "&nbsp;&nbsp;<a title='PDF report' href='index.php?sec=incidents&sec2=operation/incidents/incident_report&id=$id_incident&clean_output=1&pdf_output=1'>";
	echo "<img src='images/page_white_acrobat.png'>";
	echo "</a>";
}
	
echo '</h1>';
	
$generated_str = '<div class="report_info" style="text-align: right; width: 95%;">';
$generated_str .= print_label (__('Generated by').' : ', '', '', true,
	dame_nombre_real ($config['id_user']));
$generated_str .= '<br />';
$generated_str .= print_label (__('Date').' : ', '', '', true, date ('Y-m-d H:i', time ()));
$generated_str .= '</div>';

echo $generated_str;

$output = '<div style="margin-left: 15px; text-align: left; width: 95%;">';


$output .= '</div>';
echo '<div class="report_info" style="text-align: left; width: 95%">';
if ($output != '') {
	echo $output;
} else {
	echo __('All incidents');
}
echo '</div>';

$table->class = 'listing';
$table->width = "95%";
$table->style = array ();
$table->style[0] = 'font-weight: bold';
$table->head = array ();
$table->head[0] = __('ID');
$table->head[1] = __('SLA');
$table->head[2] = __('Incident');
$table->head[3] = __('Group');
$table->head[4] = __('Status')."<br /><em>".__('Resolution')."</em>";
$table->head[5] = __('Priority');
$table->head[6] = __('Updated')."<br /><em>".__('Started')."</em>";
$table->head[7] = __('Work');
$table->head[8] = __('Responsible');
$table->data = array ();

$incident = get_incident ($id_incident);

/*
echo '<h3>'.__('Statistics').'</h3>';

print_incidents_stats ($incidents);
*/
echo '<div style="clear: both"></div>';

if ($incident == false) {
	$table->colspan[0][0] = 9;
	$table->data[0][0] = __('Nothing was found');
}

$data = array ();

$data[0] = '#'.$incident['id_incidencia'];
$data[1] = '';
if ($incident["affected_sla_id"] != 0)
	$data[1] = '<img src="images/exclamation.png" />';
$data[2] = '<a href="index.php?sec=incidents&sec2=operation/incidents/incident&id='.$incident['id_incidencia'].'">'.
	$incident['titulo'].'</a>';
$data[3] = get_db_value ("nombre", "tgrupo", "id_grupo", $incident['id_grupo']);

$resolution = isset ($resolutions[$incident['resolution']]) ? $resolutions[$incident['resolution']] : __('None');

$data[4] = '<strong>'.$statuses[$incident['estado']].'</strong><br /><em>'.$resolution.'</em>';
$data[5] = print_priority_flag_image ($incident['prioridad'], true);
$data[6] = human_time_comparation ($incident["actualizacion"]);
$data[6] .= '<br /><em>';
$data[6] .=  human_time_comparation ($incident["inicio"]);
$data[6] .= '</em>';

$data[7] = '';
$workunits = get_incident_count_workunits ($incident["id_incidencia"]);
if ($workunits > 0) {
	$data[7] = '<img src="images/award_star_silver_1.png" />';
	$data[7] .= get_incident_workunit_hours ($incident["id_incidencia"]);
}

$data[8] = $incident['id_usuario'];

array_push ($table->data, $data);

echo '<h3>'.__('Incident summary').'</h3>';

print_table ($table);

echo '<h3>'.__('Description').'</h3>';

echo $incident['descripcion'];

echo '<h3>'.__('Epilog').'</h3>';

echo $incident['epilog'];

echo '<h3>'.__('Incident workunits').'</h3>';

$workunits = get_incident_workunits ($id_incident);

if ($workunits === false) {
	echo '<h4>'.__('No workunit was done in this incident').'</h4>';
	return;
}

foreach ($workunits as $workunit) {
	$workunit_data = get_workunit_data ($workunit['id_workunit']);
	show_workunit_data ($workunit_data, $title);
}

?>
